### ISSUE TITLE
Datasets.CDDataset (line 31)

### ISSUE THREAD

**Issue by GH-W5** [Bobholamovic/ChangeDetectionToolbox#1]
工程浩大，数据集，能分享一下吗？至少要让代码跑起来啊

**Comment by Bobholamovic** [comment]
当然，学术需要分享才能进步。数据集方面请参见：

[这个仓库](https://github.com/wenhwu/awesome-remote-sensing-change-detection)
[这个知乎回答](https://www.zhihu.com/question/52021465)
以及 [这个博客](https://zhangbin0917.github.io/2018/06/12/%E9%81%A5%E6%84%9F%E6%95%B0%E6%8D%AE%E9%9B%86/)

**Comment by wenhwu** [comment]
变化检测开源的项目还是太少了，尤其是优质的项目。一起加油。

**Comment by Bobholamovic** [comment]
> 变化检测开源的项目还是太少了，尤其是优质的项目。一起加油。

感谢大佬鼓励，一起加油！
