### ISSUE TITLE
Nan for AUC

### ISSUE THREAD

**Issue by wgcban** [Bobholamovic/ChangeDetectionToolbox#10]
Hi,

Thank you for making available this awesome Github repo, and it's really valuable. However, I'm getting NaN value for the AUC metric. Do you know why this is happening?

**Comment by Bobholamovic** [comment]
Thanks for your recognition of this work. For the NaN issue, can you provide more details about your experimental setting and the input data? BTW, have you plotted the ROC curve? An observation on the ROC curve might help us locate the problem.

**Comment by Bobholamovic** [comment]
I guess one possible reason could be that there is no *changed* pixel in the grouth-truth labels.

**Comment by wgcban** [comment]
@Bobholamovic Hey thank you for the reply. I made a mistake while reading the image. There is not a bug in your code. For now, I have tested your code for the ONERA dataset and AirChallege dataset, and it's working fine.
