### ISSUE TITLE
Does the code of DPCA match the paper?

### ISSUE THREAD

**Issue by ccc123450** [Bobholamovic/ChangeDetectionToolbox#12]
Hello,
I want to use the DPCA algorithm. When I checked the paper "PCA‐based land‐use change detection and analysis using multitemporal and multisensor satellite data", it seems that the procedure of DPCA first concatenates the multitemporal images at the 3rd dimension as the input. Then, compute the principal components and the number of PCs is the same as the input. Next,  ISODATA is adopted to produce an unlabelled cluster map and provide a basic set of classes for further supervised classification. Finally, unsupervised classification adopting a maximum likelihood algorithm was implemented.

The DPCA in this toolbox computes the PCs of the difference of the multitemporal images and classifies the PCs to generate the output.

**Comment by Bobholamovic** [comment]
Hi, the DPCA in this repo is a simple empirical implementation and I cannot find a paper that exactly describes this method. Sorry if the associated link directs to a paper that describes a different and more complex method.
