### ISSUE TITLE
readme中示例问题

### ISSUE THREAD

**Issue by fuweifuvtoo** [Bobholamovic/ChangeDetectionToolbox#2]
作者您好，非常感谢您的开源代码，感觉很有工作量。
但是希望您能多更新一点Usage在readme当中，例如您可以挑一个数据集，从下载到处理再到使用你的代码跑出结果的详细示例，这样可能更易懂一点。
公开的变化检测数据集差距还挺大，不知道哪一个比较适用再这份代码中呢？
期待得到您的回复。

**Comment by Bobholamovic** [comment]
感谢您的建议，我会添加更详细、具体的示例到README中。

由于这个仓库实现的都是基于像素的传统算法，因此可能更适合中低分辨率影像一些。实际上，有一件尴尬的事：我测试的5个数据集中，在不公开的数据——两个SAR影像对Bern和Ottawa、以及泰州数据上有较好的结果；而在公开的OSCD数据集和Air Change数据集上，所有算法的效果都不太让人满意。

通过调用`detectChange.m`，您可以较为方便地在其它中低分辨率影像上进行测试。如果您找到了合适的公开数据集，能否告知我？我将十分感激。
