### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by Daisy-7** [Bobholamovic/ChangeDetectionToolbox#3]
感谢你的分享！
我想用你的程序处理自己的数据，我在运行代码的时候报错了。
调用语句为：
`[CM,DI]=detectChange('CVA',{},'KMeans',{},path1,path2);`

报错如下：

> 错误使用 
 Algorithms.CVA
 错误:  文件:CDAlg.m 行:4 列:16
 'char' 已定义为属性。
出错 detectChange (line 39)
algCD = Algorithms.(alg_cd)(config_alg_cd{:});
小白不知道哪里有问题，还请解答，万分感谢！

**Comment by Bobholamovic** [comment]
你好，谢谢你的肯定。
我不太确定这个错误的来源，刚才我检查了一下代码，然后试着输入一样的指令（除了path1和path2以外），但似乎不能复现同样的结果。
如果方便的话，可否告知我你的MATLAB版本以及执行代码的环境（比如所在的位置等等）以便更好地定位这个错误？

**Comment by Daisy-7** [comment]
代码环境为 MATLAB R2015b windows10 64 ，文件执行时是直接调用的detectChange函数，再脚本文件下运行，path1与path2 是我自己数据的路径。当我运行main.m文件也是报同样的错。另外，请问CONFIG_XXX，这是来实现什么样的配置的呢？我看算法，数据和验证部分都有这部分内容。

**Comment by Bobholamovic** [comment]
考虑到我的环境是R2017b，我猜测这有可能是一个版本问题（我在开发的时候没有做到向后兼容）。具体来说，根据你提供的报错信息，这可能和“属性验证”功能有关，但遗憾的是我没有找到对应的release note。你可以试一试手动把`+Algorithms/CDAlg.m`中第4行和第5行中的`char`去除。类似的情况可能还出现在其它文件中。大体上，这些`char`或者其它类型说明的存在并不会过多影响代码的功能。

关于`CONFIG_XXX`配置宏，抱歉我在自述文件里可能没有写清楚。这个`CONFIG_XXX`的内容实际上会作为实参传递给对应的类的构造函数。举个例子：

对于`ThreAlgs.KMeans`来说，额外的输入参数是得到支持的。在这里
https://github.com/Bobholamovic/ChangeDetectionToolbox/blob/c42e41b7a9b097f86744757eae18beb0c43ba7e9/%2BThreAlgs/%40KMeans/KMeans.m#L6

可以看到，这个类的构造函数支持任意个输入参数。实际上，这些参数在类的内部被传递给matlab的`kmeans` API
https://github.com/Bobholamovic/ChangeDetectionToolbox/blob/c42e41b7a9b097f86744757eae18beb0c43ba7e9/%2BThreAlgs/%40KMeans/KMeans.m#L19

而这个API实际上可以接受一些额外的配置信息。通过`help kmeans`可以查看更多细节。

这样等价于将`kmeans`的一些接口暴露在`KMeans`外，如果设置
```MATLAB
THRE_ALG = 'KMeans'
...
CONFIG_THRE_ALG = {'some_key', some_val}
```

那么就等价于在`KMeans`内部调用`kmeans(cdMapReshaped, 2, 'some_key', some_val)`。

因为每个类的附加参数都可能不同，逐一添加文档说明着实是大工程。不过我在接下来的工作中会考虑更详尽的说明的。

实际上，除非需要定制一些特别的功能，这些参数一般是不会用到的。所以不必太担心，大部分时间将这些元胞数组留空即可。

**Comment by Daisy-7** [comment]
好，感谢你不厌其烦的解答！我知道你是谁了，有机会见面交流！

**Comment by Bobholamovic** [comment]
😂好的
