### ISSUE TITLE
关于图像配准问题

### ISSUE THREAD

**Issue by fuweifuvtoo** [Bobholamovic/ChangeDetectionToolbox#4]
冒昧请问，您做图像预处理的时候需要涉及到图像配准吗？
因为变化检测第一步就是图像配准，目前我用的方法达不到像素级别的精度，请问您知道哪些好的方法吗？

**Comment by Bobholamovic** [comment]
您好，遗憾地说，我实验所使用的数据集都是已经经过配准的，而我对图像配准过程知之甚少。
如果讨论“听说过”的范畴，那么我想或许我只能和您分享以下几篇我在综述中找到的文献，希望对您有帮助。
> DAI Xiaolong, KHORROM S. The Effects of Image Misregistration on the Accuracy of Remotely Sensed Change Detection[J]. IEEE Transactions on Geoscience and Remote Sensing, 1998, 36(5): 1566-1577. </br>
CHEN Gang, ZHAO Kaiguang, POWERS R. Assessment of the Image Misregistration Effects on Object-based Change Detection[J]. ISPRS Journal of Photogrammetry and Remote Sensing, 2014(87): 19-27. </br>
MARCHESI S, BOVOLO F, BRUZZONE L. A Context-Sensitive Technique Robust to Registration Noise for Change Detection in VHR Multispectral Images[J]. IEEE Transactions on Image Processing, 2010, 19(7): 1877-1889. </br>
VAKALOPOULOU M, KARANTZALOS K, KOMODAKIS N, et al. Graph-based Registration, Change Detection, and Classification in very High Resolution Multitemporal Remote Sensing Data[J]. IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing, 2016, 9(7): 2940-2951. </br>
THEILER J, WOHLBERG B. Local Coregistration Adjustment for Anomalous Change Detection[J]. IEEE Transactions on Geoscience and Remote Sensing, 2012, 50(8): 3107-3116. 

实际上，我并没有仔细阅读过这些文献或是复现过其中的算法，因此您可能需要仔细辨别和斟酌。

**Comment by fuweifuvtoo** [comment]
好的 谢谢你的回答！
