### ISSUE TITLE
你好， 我遇到了“矩阵接近奇异值，或者缩放错误。结果可能不准确。”

### ISSUE THREAD

**Issue by ghost** [Bobholamovic/ChangeDetectionToolbox#5]
你好，我在使用MAD运行“shuguang”，“sardinia”，”yellow river“这样的异质遥感数据集时候，会提示”警告: 矩阵接近奇异值，或者缩放错误。结果可能不准确。“然后无法运行IRMAD算法。
我觉得是我使用方式有问题，请问在使用这种数据集时候该如何使用。

运行代码如下
`[CMs, DIs, results] = detectChange('IRMAD', {}, 'OTSU', {}, 't1.jpg', 't2.jpg', 'gt.jpg', {'OA', 'Kappa'}, {{}, {}});
`

**Comment by Bobholamovic** [comment]
你好，我认为这很有可能和所使用的数据相关。我在实验中也碰到过类似的问题，我的问题是由于**多个波段具有完全相同的数据**导致求解广义特征值过程失败，或许你应该检查一下自己的数据是否有类似的情况？（一个常见的情形是：出于方便显示之类的原因某些三波段影像实际上只是将灰度影像的灰度值完全复制到RGB三个波段，这实际上仍等价于单波段影像，因而不在PCA等方法的适用范围内）

**Comment by ghost** [comment]
感谢您的回复。
我用到的数据集就是你说的这样，其中光学图像是3通道的，但是SAR图像也是3通道，计算出来的DIs矩阵其中第一通道和第三通道都是NAN，导致后面运算不下去。
按照您的经验，我应该如何处理数据集使得程序可以运行（换句话说，IRMAD和MAD要求的输入图像格式是怎样的？）

Lin Manhui <notifications@github.com> 于2020年1月6日周一 上午11:07写道：

**Comment by Bobholamovic** [comment]
按照我有限的理解，IRMAD和MAD都做了类似波段加权的操作，所以它们可能更适用于波段数较多的情形。我不确定是否完全明白您的意思——您是指数据集的一个影像对中一幅是3通道光学影像，另一幅是3通道SAR影像，同时两幅影像都存在波段数据上的冗余吗？如果是这样的话，这等价于您只有一个波段的光学影像和一个波段的SAR影像。在这种情况下，我想诸如DPCA、PCDA、IRMAD、MAD这样对波段执行线性变换和降维的算法应该都是不太适合的……如果我的理解有误，请纠正我。

**Comment by ghost** [comment]
我刚入手做异质遥感图像变化检测，看到许多文献中使用MAD/IRMAD作为对比方法，所以我也想试着跑下这个程序。
目前我使用的 “四川 shuguang village” 数据，
里面有三幅图像（别人传给我的数据，有些问题），一副彩色的光学图像，一副SAR图像（我觉得SAR应该是1通道图像，但是我获得的有3个通道），一副gt真值图像（存在问题，也是三通道）。我目前觉得是我的数据存在问题，我应该怎样调整数据才能运行MAD程序。
或者说，我需要怎样的图像对，才可以运行MAD程序

Lin Manhui <notifications@github.com> 于2020年1月6日周一 上午11:47写道：

**Comment by Bobholamovic** [comment]
首先让我确认一下，您的意思是不是：一幅3个波段相互独立的光学影像，一幅只有一个波段（两个波段冗余）的SAR影像，以及一幅变化标签（二值影像，但是有三个波段）。

如果是这样的话，请参考如下步骤以便正确运行MAD程序：
1. 将SAR影像和变化标签转换为单波段灰度影像并保存。
2. 下载本仓库的[`dev`分支](https://github.com/Bobholamovic/ChangeDetectionToolbox/tree/dev)，这是由于“处理波段数目不同的两个输入的MAD”目前仍属于测试功能，尚未从开发分支推送到主分支，而您需要用到这一功能（光学影像3个波段，SAR影像1个波段）。
3. 使用`dev`分支的`detectChange`函数运行之前的代码，注意此时需要将SAR输入以及gt标签替换为第一步中生成的单波段影像。

**Comment by ghost** [comment]
您好，非常感谢您，在dev分支下的
detectChange函数可以解决我的问题，程序可以成功运行。精确度和论文中不一样，我想可能是一些参数的问题，我去试试~Thanks

Lin Manhui <notifications@github.com> 于2020年1月6日周一 下午2:10写道：

**Comment by Bobholamovic** [comment]
不客气，很高兴能帮到您。事实上，除了您所提到的参数，还有两个可能的原因导致结果不同：
1. dev分支相比master分支未经过充分测试，因此是不够稳定的，其中可能包含更多的bug，也即代码的编写可能有错误。
2. 在算法的具体细节上，不同的实现版本可能有一些区别，这将导致指标不完全一致。例如，我在算法的最后添加了一个额外的归一化。

如果您需要复现完全一致的指标，即需要MAD和IRMAD的原版算法，不妨关注论文[原作者发布的版本](http://people.compute.dtu.dk/alan/software.html)。

**Comment by ghost** [comment]
非常感谢您的帮助，您的代码写的很清晰，对我帮助很大。
我在继续实验，在IRMAD中，将三通道光学图像和单通道SAR图像作为输入，总是很难达到论文里对比方法的效果。

总之非常感谢您在百忙之中抽出时间解决我的问题。

Lin Manhui <notifications@github.com> 于2020年1月7日周二 上午10:30写道：
