### ISSUE TITLE
一点点matlab语法的问题

### ISSUE THREAD

**Issue by CanoeByGuitar** [Bobholamovic/ChangeDetectionToolbox#6]
你好，因为本人几乎不用matlab，这里调用你的程序试验一下CVA算法的结果的，但是出了以下问题
```
>> [CM, DI] = detectChange('CVA', {}, 'KMeans', {}, '2015img_gray.tif', '2018img_gray.tif')
警告: The rank of the input image is detected to be lower than 2. 
> In detectChange>cd4Pair_ (line 116)
  In detectChange (line 54) 
元胞内容引用自非元胞数组对象。

出错 ThreAlgs.KMeans/segment (line 19)
            CM = uint8(reshape(kmeans(cdMapReshaped, 2, obj.params{:}), rows, cols));

出错 detectChange>cd4Pair_ (line 120)
CM = alg_thre.segment(DI);

出错 detectChange (line 54)
    [varargout{:}] = cd4Pair_(algCD, algThre, varargin{:}, '', {}, {});
```
应该是matlab数据结构上的问题吧，我不太清楚怎么解决。
另外，这个程序是不是只能用来对单通道的灰度图处理，因为我放进三通道的图片一直报矩阵维数错误

**Comment by Bobholamovic** [comment]
您好，关于这两个问题我做了一些测试，回复如下：
1. 针对`元胞内容引用自非元胞数组对象`的问题，考虑到您的调用语法完全符合要求，我怀疑可能是一个版本兼容性问题。为此，请确认您的MATLAB版本在R2017b以上。
2. 针对输入图像维度的问题，实际上这个程序被设计为可以处理任意通道的图像。如果您所说的“维数错误”指的是运行输出第一行的`警告: The rank of the input image is detected to be lower than 2. `，这其实是一个新添加的功能，这一检测表明您的输入数据的三个通道数据很可能完全相同（即只是将单通道灰度图通过复制拓展到了三个通道）。在这种情况下，如果使用基于主成分分析的算法，很可能得到一个错误，这也是添加这一预检测的初衷。为此，请检查您的数据是否符合这一描述。

如果确认是程序bug，请及时汇报给我，谢谢！

**Comment by CanoeByGuitar** [comment]
非常感谢你的回复，第二个问题我已解决，第一个问题可能确实是我matlab版本引起的。
最后想请教一下，你demo里的图`prettified results`，实现的方法是什么，写在哪个路径哪个文件里，谢谢！

**Comment by Bobholamovic** [comment]
https://github.com/Bobholamovic/ChangeDetectionToolbox/blob/8ba5f4e3ab6654d9d5e1bcfbb5cff619aa6a240e/%2BUtilities/pretty.m#L1

是在这个地方实现的。实现的具体方法是：给定一张变化图`seg_map`，一张差值图`cd_map`，一张标签图`ref_map`，以及一个（可选的）调色板参数。将归一化后的`cd_map`作为背景，对于多波段的情形先取各波段逐像素均值。根据`seg_map`和`ref_map`，可以得到TP（正确分出的变化区域）、FP（误检区域）、TN（正确分出的未变化区域）、FN（漏检区域）对应的像素点，然后使用调色板中指定的参数分别对这些像素点用不同的颜色进行填充，得到prettified image。

实际上，这里的`ref_map`支持三种格式。`README.md`中展示的情况包含*采样区域*，即只在*采样区域*上计算混淆矩阵，最终着色也只会影响这部分区域，未采样区域则用背景图填充。为了实现这个功能，一种方式是将`ref_map`中您不希望着色的区域用数字`2`填充，变化区域用`1`填充，不变区域用`0`填充。您可能需要手动实现这一功能。另外一种情况是：预先采样好的真值标签可能被存储在分隔的文件里，如`ref_change.png`以binary mask的形式存储了变化的标签，用`True`表示变化像素点；而`ref_nochange.png`同样以binary mask的形式存储了不变的标签，用`True`表示不变像素点。显然，`ref_change.png`和`ref_nochange.png`中的所有`True`值可能不涵盖图像中所有的像素点，那么剩下未被标记的部分就是未采样的部分。作为处理这种情况的手段，工具箱中提供了
https://github.com/Bobholamovic/ChangeDetectionToolbox/blob/8ba5f4e3ab6654d9d5e1bcfbb5cff619aa6a240e/%2BMetrics/%40CDMetric/CDMetric.m#L118
静态方法，将`ref_change.png`和`ref_nochange.png`拼接为两波段影像，作为`ref_map`参数输入到`pretty`函数中，也能实现一样的效果。
