### ISSUE TITLE
关于IRMAD算法的问题

### ISSUE THREAD

**Issue by Fanrongbo** [Bobholamovic/ChangeDetectionToolbox#7]

**Comment by Fanrongbo** [comment]
请问算法中inv(cov21)@cov21@a=ρ@b，为什么在程序中inv(cov21)@cov21@a=b

**Comment by Fanrongbo** [comment]
补充：@为点乘，ρ为特征值

**Comment by Bobholamovic** [comment]
不好意思，我可能还是没有太领会你的意思。可以更详细一些，比如给出可能出错的代码所在的行数吗？

**Comment by Fanrongbo** [comment]
没有错误，我只是想和你交流一个问题。我最近在学习IRMAD算法，对比了很多代码，总体上有两种写法，
一种是分别分解inv(sigma_11)@sigma_12@inv(sigma_22)@sigma_21和inv(sigma_22)@sigma_21@ inv(sigma_11)@ sigma_12得到特征向量a，b。
请问ChangeDetectionToolbox/+Algorithms/@IRMAD/detectChange.m文件中42行和47行的注释正相关是什么意思，或者有什么资料文献可以介绍一下吗？

**Comment by Fanrongbo** [comment]
另一种是仅分解inv(sigma_11)@sigma_12@inv(sigma_22)@sigma_21得到特征值ρ和特征向量a，然后inv(sigma_21)@sigma_21@a=b,这个方法没有关于”正相关“的约束。但是论文中inv(sigma_21)@sigma_21@a=ρb与算法差一个ρ。
我实验发现这两种算法的结果是一模一样的！

**Comment by Bobholamovic** [comment]
我才疏学浅，只能理解第一种写法，这和论文[1]附录部分的推导是一致的。至于42行和47行的正相关，实际上是为了满足[1]中对公式(5)

> We shall request that aTX and bTY are positively correlated.

的条件。这是因为如果这个相关不恒为正数的话，后一句

> Determining the difference between linear combinations with maximum variance corresponds to determining linear combinations with minimum (non-negative) correlation

就没有意义了。

> [1] Nielsen, A. A., Conradsen, K., & Simpson, J. J. (1998). Multivariate Alteration Detection (MAD) and MAF Postprocessing in Multispectral, Bitemporal Image Data: New Approaches to Change Detection Studies. Remote Sensing of Environment, 64(1), 1–19.

**Comment by Fanrongbo** [comment]
好的，万分感谢！

**Comment by Fanrongbo** [comment]
实在不好意思啊，我还是没有搞懂aTX 和bTY正相关为什么用代码中的方式表示？这个有什么数学推导吗？

**Comment by Bobholamovic** [comment]
抱歉是我之前没解释清楚，实际上第42行和47行对应的部分是两样不同的东西：前者是[原作者的代码](http://people.compute.dtu.dk/alan/software.html)中采用的一个步骤，论文里似乎没提到。我对原来的代码做了一些简化，但不是很理解这个步骤的意义（也许在工程实现上提供了某种便利或者使得结果保持更优雅的形式？），不确定这是否是一个必要的步骤，所以就把它保留了下来。后者才是我之前说的，迫使aTX和bTY正相关。这个我觉得大致可以这样理解：对于特征值和特征向量我们有

```
Px = vx
``` 

`P`是原矩阵，`x`是特征向量，`v`是特征值。如果对等式两边同乘以一个负号，这个式子显然也还是成立，那也就是说`-x`肯定也是特征值`v`对应的一个特征向量。所以我们用`sign`函数来取符号，通过对特征矩阵`b`乘以1或者-1来保证各个分量和对应的`a`中的分量正相关。

**Comment by Fanrongbo** [comment]
谢谢你！遇到这么负责的也太不容易了
