### ISSUE TITLE
Password and Username - SZTAKI Air Change

### ISSUE THREAD

**Issue by ucalyptus** [Bobholamovic/ChangeDetectionToolbox#8]
Hi @Bobholamovic can you share the password and username.
The email mentioned on the site hasn't replied me yet.

Thank you,
Sayantan Das
http://ucalyptus.github.io/

**Comment by Bobholamovic** [comment]
Well, I’m not sure whether it is suitable to post the password and username public here, but I would send them to your personally if you could provide your email address.

发件人: Sayantan Das<mailto:notifications@github.com>
发送时间: 2020年8月15日 0:24
收件人: Bobholamovic/ChangeDetectionToolbox<mailto:ChangeDetectionToolbox@noreply.github.com>
抄送: Lin Manhui<mailto:bob1998425@hotmail.com>; Mention<mailto:mention@noreply.github.com>
主题: [Bobholamovic/ChangeDetectionToolbox] Password and Username - SZTAKI Air Change (#8)


Hi @Bobholamovic<https://github.com/Bobholamovic> can you share the password and username.
The email mentioned on the site hasn't replied me yet.

Thank you,
Sayantan Das
http://ucalyptus.github.io/

―

**Comment by ucalyptus** [comment]
@Bobholamovic I received it.

**Comment by wgcban** [comment]
Hi,
@Bobholamovic @ucalyptus can one you please share the password with me? My email: wbandar1@jhu.edu.
Thanks.
